server:
  port: 9004
spring:
  application:
    name: sc-redis
  redis:
    host: 192.168.1.106
    password:
    port: 6379
    timeout: 10000
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
